name: Create Release Tag

on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'develop')
    steps:
      - uses: actions/checkout@v2

      - name: Get Version Name
        run: echo "VERSION_NAME=ver$(./gradlew -q getAppVersionName)" >> $GITHUB_ENV
      - name: Create Release Tag
        uses: actions/github-script@v6
        with:
          debug: true
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const env = process.env
            const tagResult = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: env.VERSION_NAME,
              message: '',
              object: context.sha,
              type: 'commit',
            })

            const referenceResult = await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${env.VERSION_NAME}`,
              sha: context.sha
            });
