name: Create Release Tag

on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'develop')
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Create Release Tag
        run: |
          git tag ver$(./gradlew -q getAppVersionName)
          git push origin ver$(./gradlew -q getAppVersionName)
