name: Create Release Tag

on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'develop')
    steps:
      - name: Create Release Tag
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const versionName = ver$(./gradlew -q getAppVersionName | tail -n 1)

            github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: versionName,
              message: '',
              object: context.sha,
              type: 'commit',
            })
